### ISSUE TITLE
Multi-origin SSL check

### ISSUE THREAD

**Issue by phawxby** [jsbnr/nr-bulk-ssl-checker#1]
It would be good if this project could enhanced so that you query individual IP addresses and validate the the certificate for a hostname on each. For example we have an application hosted in 3 regions with a load balancer automatically distributing traffic based on proximity, the SSL certs need to be up to date in all 3 regions. 

There's another use-case for intermediate hosts for example you have your origin host application and then you have a Web Application Firewall in front of that such as Akamai, Imperva, etc. In these cases you need the cert to exist and be up to date in both places. 

Happy to have one of the team work on this and PR it back if you'd be open to such a change.

**Comment by jsbnr** [comment]
Hi Paul, I would be happy to merge in a feature such as that proposed. Let me know if you need any assistance.
